spring:
  application:
    name: tibiaidle
  mvc:
    static-path-pattern=/static/**
  resources:
    static-locations=classpath:/static/
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
# JWT
jwt:
  expires-in: 300
  private:
    key: classpath:config/app.key
  public:
    key: classpath:config/public.key

# Google
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
